application: pi4wfgen
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /.*
  script: pi4gae.application
  secure: always
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
